name: Terraform GitHub Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev
      - test
  
env:
  TF_VERSION: 1.14.0
  AWS_REGION: eu-west-2
  AZURE_REGION: uksouth
  GCP_REGION: europe-west2

jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate - dev
        run: terraform init -backend=false && terraform validate -var-file=dev.tfvars